import { readFileSync, writeFileSync } from 'node:fs'

const manifest = JSON.parse(readFileSync(new URL('../packages/registry/registry/themes/registry.json', import.meta.url), 'utf8'))
const theme = manifest.items[0]
const declarations = (values) => Object.entries(values).map(([key, value]) => `  --${key}: ${value};`).join('\n')
const css = `/* Generated by pnpm theme:build from the installable eva-theme. */\n${Object.keys(theme.css).map(rule => `${rule};`).join('\n')}\n\n@theme inline {\n${declarations(theme.cssVars.theme)}\n}\n\n:root, .eva-theme-light {\n${declarations(theme.cssVars.light)}\n}\n\n.dark, .eva-theme-dark {\n${declarations(theme.cssVars.dark)}\n}\n`
const target = new URL('../apps/docs/src/app/eva-theme.css', import.meta.url)
if (process.argv.includes('--check')) {
  if (readFileSync(target, 'utf8') !== css) throw new Error('Theme CSS is stale. Run pnpm theme:build.')
} else writeFileSync(target, css)

const license = readFileSync(new URL('../LICENSE', import.meta.url), 'utf8')
const registryLicense = new URL('../packages/registry/registry/themes/LICENSE', import.meta.url)
if (process.argv.includes('--check')) {
  if (readFileSync(registryLicense, 'utf8') !== license) throw new Error('Registry license is stale. Run pnpm theme:build.')
} else writeFileSync(registryLicense, license)
